// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations need unpooled URL (Neon) to avoid advisory lock timeout; runtime uses pooled in lib/prisma.ts
  datasource: {
    url:
      process.env["DATABASE_URL"] ??
      process.env["NETLIFY_DATABASE_URL_UNPOOLED"] ??
      process.env["NETLIFY_DATABASE_URL"],
  },
});
